### ISSUE TITLE
mux-r2.8.0 sends "Player is accessed on the wrong thread" warning

### ISSUE THREAD

**Issue by kai-sarawut** [muxinc/mux-stats-sdk-exoplayer#12]
After updating version to mux-r2.8.0 I notice that "Player is accessed on the wrong thread" warning is sent repeatedly in Logcat console. The last version has no this issue so I suspect that this could possibly affect ExoPlayer performance on my application? Or this is a known issue?  How can I handle with this issue? Thanks.

**Comment by kai-sarawut** [comment]
![messageimage_1548225295823](https://user-images.githubusercontent.com/15886164/51646570-aa631680-1fab-11e9-9f39-35e461b7c337.jpg)

**Comment by jsanford8** [comment]
Hi @kai-sarawut - as of right now, this should be a warning based on the threading model that ExoPlayer has taken as of ExoPlayer 2.9.0, but we are looking at how we can address this moving forward. Are you seeing this impact playback within the application?

**Comment by kai-sarawut** [comment]
Hi, @jsanford8. Good to know this issue is going be addressed. 
At first I had playback related issue on the application and started to investigate the real problem til found out the issue caused by integration with another third-party code.  Until now I don't have a visible impact on the application with this issue, but I wonder this could have an effect on player in the future.

**Comment by jsanford8** [comment]
Hi @kai-sarawut - absolutely! This is why we're looking into fixing this moving forward, because Google may change this into a hard exception in the future, potentially, or some other issue. I will provide updates on this issue as we have them.

**Comment by OMArikan** [comment]
Hi @jsanford8 - my suggestion is letting pass Looper on constructor of "MuxStatsExoPlayer" likewise "ExoPlayerFactory.newSimpleInstance()".
SimpleExoPlayer.eventHandler is private final and you can't reach it from ExoPlayer object that passed in your constructor . Please don't use "Looper.getMainLooper()" because not everyone using default Looper in ExoPlayer like me.
Looking to hear from you soon 2.9.x update.

**Comment by kai-sarawut** [comment]
I think it's a thread issue in an operation in the libs.

**Comment by jsanford8** [comment]
@OMArikan thanks for the suggestion, we'll look into that!

@kai-sarawut - We do have an internal task that loops, querying the player's current playhead position, similar to this comment on ExoPlayer's issue about threading: https://github.com/google/ExoPlayer/issues/4463#issuecomment-417435600. We're trying to come up with a way to do this correctly.

**Comment by OMArikan** [comment]
Hi @jsanford8 it's been so long we have not heard any updates from you. Waiting mux-r2.9.0.aar.

**Comment by stufan** [comment]
I integrated mux-2.8.0 version and experience exactly the same issue. ExoPlayer version is 2.10.1 (the latest as of today). Any updates?

**Comment by sezn** [comment]
Yeah, it's very disappointed, two years late no new Version. It s just a warning, so, if it s just mux who dont work has expected... no matter.

**Comment by jsanford8** [comment]
fixed by #20
