### ISSUE TITLE
2.4.12 - CustomerData - Obfuscated class?

### ISSUE THREAD

**Issue by indieboyalex** [muxinc/mux-stats-sdk-exoplayer#130]
New version of SDK - 2.4.12 for ExoPlayer 2.13.1.

With the old MuxStatsExoPlayer constructors being deprecated I've followed the example which created a com.mux.stats.sdk.core.model.CustomerData object and passes this in to the new constructor.  However, we are unable to resolve this class name.  Looking into the aar file I can see that this class has been obfuscated. I'm assuming this is a mistake? 

<img width="1645" alt="Screenshot 2021-07-30 at 08 13 11" src="https://user-images.githubusercontent.com/851270/127609019-aafc1b1a-72ef-40c8-9eb5-f4a3bc6732b4.png">

**Comment by tomkordic** [comment]
Yes, CustomerData is something that should be public API.

**Comment by tomkordic** [comment]
Fixed: https://github.com/muxinc/mux-stats-sdk-exoplayer/commit/a4dd5073c51934c491a3f373d090c1988c5ab780

**Comment by skidder** [comment]
@iNdieboyjeff Thank you for reporting this issue, it should be resolved in the new [2.4.13 release](https://github.com/muxinc/mux-stats-sdk-exoplayer/releases/tag/v2.4.13). Please let us know if you encounter anything else!
