### ISSUE TITLE
When i imported the laest .aar & hit re-build faced problem encoding configuration. had to reinstall Android Studio

### ISSUE THREAD

**Issue by rommansabbir** [muxinc/mux-stats-sdk-exoplayer#14]
![image](https://user-images.githubusercontent.com/25950083/60658469-13ad5680-9e75-11e9-814c-b0d167cf071e.png)
![image](https://user-images.githubusercontent.com/25950083/60658495-1f008200-9e75-11e9-93ea-dbe82d5e070b.png)

**Comment by jsanford8** [comment]
Hey @rommansabbir - that's very odd. Importing the ARR should not have caused that type of problem, as far as we're aware. 

We've imported the latest ARR into a few projects again and haven't faced the issue you're seeing. Were you able to get up and running eventually?
