### ISSUE TITLE
ExoPlayer 2.15.x support

### ISSUE THREAD

**Issue by jjszolno** [muxinc/mux-stats-sdk-exoplayer#167]
We need a version that supports ExoPlayer 2.15.

We are currently using 2.15 with the 2.14 version of the plugin but this caused some crashes when playing video (player worked fine without the plugin so it's not the player implementation).

ExoPlayer 2.15 fixes several issues that were affecting all our Android users.

**Comment by mdale** [comment]
+1

**Comment by jsanford8** [comment]
Thanks for submitting this! We are working on an update to support r2.15.x and will update you as we make progress.

**Comment by chladto1** [comment]
+1

**Comment by daytime-em** [comment]
Support for ExoPlayer 2.15.1 been added in [v2.5.7](https://github.com/muxinc/mux-stats-sdk-exoplayer/releases/tag/v2.5.7), which is now available on Artifactory, or the [release page](https://github.com/muxinc/mux-stats-sdk-exoplayer/releases/tag/v2.5.7).

Thank you for your submission!
