### ISSUE TITLE
Add ExoPlayer 2.16.1 support

### ISSUE THREAD

**Issue by denis-bezrukov** [muxinc/mux-stats-sdk-exoplayer#183]
Exoplayer released [2.16.x](https://github.com/google/ExoPlayer/releases/tag/r2.16.1) and we would love to update our app to it. Usually, major exoplayer's versions are incompatible, so mux SDK will block us from updating. I'm posting this issue for visibility

**Comment by skidder** [comment]
@denis-bezrukov Thank you for filing this issue! We're investigating the addition of support for Exoplayer 2.16 and will keep you updated.

**Comment by daytime-em** [comment]
Thank you for reporting this. Version 2.6.0 should be available from our mvn in the next couple of hours.

You may need to update your AGP to 7.0 and JDK to 11, if you haven't yet.

**Comment by daytime-em** [comment]
2.6.0 has now been released. Sorry for the delay, we were affected by the bintray outage.
