### ISSUE TITLE
Using `presentationChange` sets player dimensions to 0

### ISSUE THREAD

**Issue by zilinx** [muxinc/mux-stats-sdk-exoplayer#187]
Library version: 2.5.9 for ExoPlayer 2.15.1+ (https://github.com/muxinc/mux-stats-sdk-exoplayer/releases/download/v2.5.9/MuxExoPlayer-r2_15_1-release.aar) 

When using the new feature implemented in `2.5.8` to tell Mux that the video is viewing full screen, the framework will stop reporting `playerWidth` and `playerHeight` - both are set to 0 in the events printed when verbose debug logging is enabled.

Steps to reproduce:
1. when creating a session, detect that the video is showing in fullscreen and set the presentation mode using: ```muxStats.presentationChange(MuxSDKViewPresentation.FULLSCREEN)```
2.  enable full debug logging with ```muxStats.enableMuxCoreDebug(true, true)```
3. run the app and check the logs. The `PlayerData` values for `playerWidth` and `playerHeight` are set to 0.

This alone wouldn't be a problem, but it completely removes video quality metrics related to video/player size.

**Comment by daytime-em** [comment]
Thank you for your submission. This is being investigated for the upcoming 2.6.0 version.

**Comment by daytime-em** [comment]
Thanks again for reporting this. Version 2.6.0 should be available from our mvn in the next couple of hours.

You may need to update your AGP to 7.0 and JDK to 11, if you haven't yet.

**Comment by daytime-em** [comment]
2.6.0 has now been released. Sorry for the delay, we were affected by the bintray outage.
