### ISSUE TITLE
Rebuffering stats doesn't seem to match the reality

### ISSUE THREAD

**Issue by AdamGrzybkowski** [muxinc/mux-stats-sdk-exoplayer#2]
I've recently implemented mux.com to gather statistics from exoPlayer. In the dashboard, I can see that there was no rebuffering. The score is 100 and there is 0 rebuffer count. I'm pretty sure this is wrong as I had some rebuffering myself and other users also reported the issue with streaming.

**Comment by wtao-mux** [comment]
@AdamGrzybkowski can you share me your exoplayer version? I did observe something strange in v2.8.0. But it works fine for v2.6.0

**Comment by AdamGrzybkowski** [comment]
@wtao-mux I'm using ExoPlayer 2.8.0, I do use Player.BUFFERING state myself I and works ok, so not sure what might be the problem

**Comment by wtao-mux** [comment]
The issue is v2.8.0 reports an runtime exception while a socket connection is temporary reset due to poor network condition. The exception resets an internal state in our SDK. We will provide a fix very soon.

**Comment by jsanford8** [comment]
Hey @AdamGrzybkowski  - we just released v0.4.2 that should hopefully fix this issue. Please feel free to re-open this issue if you still see this occurring.

**Comment by AdamGrzybkowski** [comment]
@jsanford8 It looks like the issue still exists. Maybe I can send you via private email more info so you can check the exact project?

**Comment by wtao-mux** [comment]
@AdamGrzybkowski hey Adam, this is Wenwei. I am working on any android related issues. The previous fix is about stopping rebuffering while in poor network condition. I would like to see more detail about this issue, please send your investigation to wtao@mux.com. Thanks

**Comment by AdamGrzybkowski** [comment]
@wtao-mux I've been trying to contact you via email but it tells me that your email is disabled. Did it change?

**Comment by jsanford8** [comment]
hey @AdamGrzybkowski - send the email to me (justin@mux.com) and I'll make sure it gets answered.
