### ISSUE TITLE
2.7.0 - Package missing

### ISSUE THREAD

**Issue by indieboyalex** [muxinc/mux-stats-sdk-exoplayer#202]
<img width="1018" alt="Screenshot 2022-04-22 at 08 29 09" src="https://user-images.githubusercontent.com/851270/164616880-be01eeb7-7036-44ff-b7d7-94ce959ef3a5.png">

Updated to 2.7.0 for Exo 2.16.1 and the core package is missing.  If there has been a fundamental change like this it should be in the release notes (and I can't see any reference to this), or there is an issue with the build (this has happened before so checking)

**Comment by indieboyalex** [comment]
<img width="436" alt="Screenshot 2022-04-22 at 08 35 14" src="https://user-images.githubusercontent.com/851270/164617205-c01f8036-24a0-41f3-bd24-17ad98fe7863.png">

2.6.1 looks to have a lot more packages in the aar

**Comment by daytime-em** [comment]
Thank you for your report. This change was not intended and a fix will be available very soon. We're sorry for any inconvenience this has caused

**Comment by daytime-em** [comment]
This issue has been fixed in our `v2.7.1` update. The `core` packages should be available to you again. The update is available now.

Thank you again for your report!

**Comment by indieboyalex** [comment]
<img width="551" alt="Screenshot 2022-04-29 at 09 13 02" src="https://user-images.githubusercontent.com/851270/165899910-9684d114-ddf1-45e9-85e4-4da1d9c5cd18.png">

Hate to be a pain but I have exactly the same issue with 2.7.1
