### ISSUE TITLE
Crash when timeline changes after clearing media items.

### ISSUE THREAD

**Issue by kylebrocklc** [muxinc/mux-stats-sdk-exoplayer#252]
Receiving a crash:

I've tried multiple exoplayer and mux versions.

Mux: 3.1.0
ExoPlayer: 2.18.1

java.lang.IndexOutOfBoundsException
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.Timeline$1.getWindow(Timeline.java:965)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.Timeline.getWindow(Timeline.java:1085)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.mux.stats.sdk.muxstats.internal.ExoAnalyticsListener.onTimelineChanged(ExoAnalyticsListener.kt:87)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.analytics.AnalyticsCollector.lambda$onTimelineChanged$33(AnalyticsCollector.java:576)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.analytics.-$$Lambda$AnalyticsCollector$J2ak5u9-h8YKLNPRdqAY9RZtP-I.invoke(Unknown Source:6)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:261)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:206)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.analytics.AnalyticsCollector.sendEvent(AnalyticsCollector.java:897)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.analytics.AnalyticsCollector.onTimelineChanged(AnalyticsCollector.java:573)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$9(ExoPlayerImpl.java:1268)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$s87MOCoD68VG7BJLWqHTmwcZoE0.invoke(Unknown Source:6)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:261)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1366)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.removeMediaItems(ExoPlayerImpl.java:493)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.SimpleExoPlayer.removeMediaItems(SimpleExoPlayer.java:1173)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.BasePlayer.clearMediaItems(BasePlayer.java:84)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.ForwardingPlayer.clearMediaItems(ForwardingPlayer.java:133)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at youversion.media.service.MediaService$MediaPlaybackPreparer.onPrepareFromMediaId(MediaService.kt:631)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onPrepareFromMediaId(MediaSessionConnector.java:1319)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onPrepareFromMediaId(MediaSessionCompat.java:1841)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1599)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-10 08:46:47.502  6336  6336 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by daytime-em** [comment]
Thank you for your report. We should have a fix for this later today.

**Comment by daytime-em** [comment]
@kylebrocklc `v3.1.1` of our SDK for ExoPlayer should fix this issue. It will be available sometime in the next half hour. Thank you again for your report!
