### ISSUE TITLE
Multiple events entries shown on mux dashboard

### ISSUE THREAD

**Issue by Dilip-007** [muxinc/mux-stats-sdk-exoplayer#282]
I'm using exo player version `2.18.2` & Mux dependency is `com.mux.stats.sdk.muxstats:MuxExoPlayer_r2_18_1:$3.3.1`

Now when I play some video it logs multiple entries on mux dashboard.
Out or all entries only one entry is having correct data & remaining entries are having null data (N/A) in each field

![screenshot-dashboard mux com-2023 03 15-19_09_03](https://user-images.githubusercontent.com/126069505/225640878-d49492a3-dcfc-401f-b3d4-a6226bcacc09.png)

**Comment by daytime-em** [comment]
Sorry you're having duplicated views, that is certainly not expected. We are now investigating internally. Thank you for your report!

**Comment by daytime-em** [comment]
@Dilip-007 Thanks for bearing with us as we investigate your issue.

Would you be able to verify that you are calling `MuxStatsExoPlayer.release()` when the user is done consuming your media? This is required, or else subsequent playback sessions may be recorded this way.

Can you also examine the `View ID` of your duplicate views, and if they are the same across all the duplicated views, or if they are different?

Thank you!

**Comment by daytime-em** [comment]
Hello @Dilip-007, I hope the message find you well. Were you able to try any of the suggestions above? Please let me know if you require additional assistance :)

**Comment by Dilip-007** [comment]
Hi team,
Thanks for the support. I was calling `MuxStatsExoPlayer.release()` multiple times. Issue is identified & fixed now.

**Comment by daytime-em** [comment]
Thanks for your update. I'm happy you were able to resolve your issue!
