### ISSUE TITLE
Integration of AAR is not straight forward in multi-module projects

### ISSUE THREAD

**Issue by jhowens89** [muxinc/mux-stats-sdk-exoplayer#30]
Hello,

As far as I can tell, mux releases are only delivered in the form of AARs. This becomes an issue in multimodule projects where a library module depends on mux. This is because the android gradle plugin has never officially supported "fat AARs". This is rarely an issue, because most all dependencies are available via a remote repository. In fact, we have ~80 dependencies and mux is the only aar in the project. 

Can mux make their latest releases available through a remote repository? If not, what is the recommended path?

**Comment by bearcattom** [comment]
+1 on this..  How about making the releases available via JitPack?

**Comment by bearcattom** [comment]
If you could make the releases available here...that would be HUGE.

https://jitpack.io/#muxinc/mux-stats-sdk-exoplayer

**Comment by skidder** [comment]
We resolved this in the Exoplayer SDK release 2.5.2 by making the SDK artifacts available via Maven. Please check out the [installation docs](https://docs.mux.com/guides/data/monitor-exoplayer#1-install-the-mux-data-sdk) for detailed instructions!

**Comment by bearcattom** [comment]
@skidder - THANK YOU !
