### ISSUE TITLE
Mux plugin 3.3.3 crashing app

### ISSUE THREAD

**Issue by BucherTomas** [muxinc/mux-stats-sdk-exoplayer#300]
I'm stepping in here for our dev team so please bear with any inconsistencies in this report.

We have recently upgraded our Android player SDK to the latest Mux version 3.3.3 from previous 2.5.7. However, right away it brought many instabilities with our test streaming app crashing immediately after initializing player, sometimes when entering fullscreen and so on. No data being received in the dashboard.

From my undestanding, there was a number of changes introduced in version 3.0.0, namely removing some stuff like CustomerPlayerData. Our dev team comments, though, that the Mux plugin code for ExoPlayer 2.18.1+ 

![studio64_EVnoTaInU7](https://user-images.githubusercontent.com/18445121/231438019-141d49a2-fd23-4639-bcfb-e06d4d4ac8bd.png)

 still contains these classes and our player SDK is still using them. When I look at one of the attached stack traces, it directly complains about CustomerPlayerData, so it appears there's a connection.

Are you able to glean from the attached bug report and stack traces if that is the case and can you please comment on why these classes are still available if they were mentioned as deleted?
Can you then please confirm that everything is in order in Mux plugin 3.3.3 and if our first course of action in that case is now adhering to changes listed in https://github.com/muxinc/mux-stats-sdk-exoplayer/releases/tag/v3.0.0 or is there something else?

Thanks.

[bugreport-POT-LX1EEA-HUAWEIPOT-L21-2023-04-12-09-37-10.zip](https://github.com/muxinc/mux-stats-sdk-exoplayer/files/11210558/bugreport-POT-LX1EEA-HUAWEIPOT-L21-2023-04-12-09-37-10.zip)
[d454be4a-c82b-5da1-a021-285efe0af239.log](https://github.com/muxinc/mux-stats-sdk-exoplayer/files/11210561/d454be4a-c82b-5da1-a021-285efe0af239.log)
[a723781a-c0eb-54f0-a0dc-5fbe1ecd907a.log](https://github.com/muxinc/mux-stats-sdk-exoplayer/files/11210562/a723781a-c0eb-54f0-a0dc-5fbe1ecd907a.log)

**Comment by daytime-em** [comment]
Thank you for your very thorough report! 

For the record `CustomerPlayerData` should still be in the SDK, via a `CustomerData` container object. I wasn't able to reproduce this crash using my testing app, but I maybe still be able to help.
 
Can you also verify whether or not you're using any `content {` filters on your Gradle `repository` declarations (such as `includeGroup`, etc)

Thanks again!

**Comment by BucherTomas** [comment]
Thank you for your response and hints. It has helped.

 Good news, the crashing issue was in the end on our side and was in fact somewhat unrelated to Mux plugin itself. It was caused by the building procedure concerning redistribution of our player.
