### ISSUE TITLE
Jetpack Media3 support?

### ISSUE THREAD

**Issue by devjn** [muxinc/mux-stats-sdk-exoplayer#308]
ExoPlayer is going to be deprecated and replaced with [Jetpack Media3](https://github.com/androidx/media) library. Do you have plans to support it?
It should be a seamless transition as it currently corresponds to ExoPlayer code except package naming?
Here is a migration guide:
https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide

**Comment by daytime-em** [comment]
Hi! Thank you for your interest. 

We have a Media3 SDK [available in public beta](https://github.com/muxinc/mux-stats-sdk-media3) right now. All relevant APIs and most basic Mux Data features are already supported, with more advanced features to come. Please give it a try and let us know what you think!
