### ISSUE TITLE
Host mux-stats-sdk-exoplayer on Maven

### ISSUE THREAD

**Issue by jsanford8** [muxinc/mux-stats-sdk-exoplayer#32]
Or some such place. The issue is that transitive dependency resolution cannot be performed on AARs included directly in the libs folder. This would also simplify the inclusion of our SDK within applications that use ExoPlayer.

We should investigate jcenter and whether we can host our AAR there (with all of the different versions/flavors) correctly, to make people's lives easier.

We have this _almost_ complete here:
https://github.com/muxinc/mux-stats-sdk-exoplayer/pull/9
https://github.com/muxinc/mux-stats-sdk-java/pull/21

**Steps**
 - [] Finish Javadocs for Muxcore
 - [] Finish Javadocs for Exoplayer
 - [] Review Javadocs
 - [] Modify the README for Exoplayer to include integration steps for Maven dependency
 - [] Modify public docs on docs.mux.com with integration steps

**Comment by jhowens89** [comment]
Is there any update on this?

**Comment by bearcattom** [comment]
Bumping this issue...we really need this!

**Comment by Oziomajnr** [comment]
Please is there a timeline for this? I need to add mux mux-stats-sdk as a transitive dependency too.
