### ISSUE TITLE
Missing hb events

### ISSUE THREAD

**Issue by kamilpierudzki-vimncontractor** [muxinc/mux-stats-sdk-exoplayer#357]
Hello the Mux team,

I have a problem with hearbeat evens in the app. We are currently using:
- MUX: `com.mux.stats.sdk.muxstats:MuxExoPlayer_amznPort (v3.4.7)`
- ExoPlayer: `com.amazon.android:exoplayer-* (v2.18.7)`
I'm able to see events like `"e": "play"`,`"e": "pause"` but I can't see `"e": "hb"`. Instead of the hb events we can see the app sends `"e": "requestcompleted"` every few seconds. Some time ago we have been using:
- MUX: `com.mux.stats.sdk.muxstats:MuxExoPlayer_r2_11_1 (v3.1.0)`
- ExoPlayer: `our implementation of the amazon player based on v2.11.3-41`
Back then we were able to see the hb events. We didn't change the code between versions.

I tried to figure this out by myself but I stuck. Shall we expect the hb events in the newest version of the sdk?

**Comment by daytime-em** [comment]
Hello! Sorry for the delay getting back to you.

The short answer is that you shouldn't have to worry about `hb` events being sent. They may still be sent under some circumstances, but if you are using bandwidth metrics then you will probably see fewer `hb` events. We only send `hb` if no event was sent for 10 seconds, and bandwidth metrics send events every time a request for a segment/chunk is started or completed.

You mentioned updating from a player based on `r2.11.1` to one based on `r2.18.7`. This is likely the cause of the change in behavior, as bandwidth metrics are not supported in the `MuxExoPlayer_r2_11_1` variant of our SDK, (edit: But *are* supported in our `amznPort` variant).

Are you seeing any issues with data quality after the upgrade?

**Comment by daytime-em** [comment]
Since I haven't heard back, I'll close this issue.

Please feel free to repoen if you need anything else!
