### ISSUE TITLE
Live's duration and progress are wrong

### ISSUE THREAD

**Issue by nvhaiwork** [muxinc/mux-stats-sdk-exoplayer#45]
I'm trying to play a live streaming by the example and saw that duration and progress of streaming are in correct. Duration starts then increases to 40(or 20) then stop and progress will become -1 after a while

**Comment by jsanford8** [comment]
Hi @nvhaiwork thanks for reaching out. When you say `progress` and `duration`, what are you referring to within Mux? Is `duration` the `video_source_duration` field, and is `progress` the playhead position?

**Comment by nvhaiwork** [comment]
![93649089_556944768288275_8985548397616300032_n](https://user-images.githubusercontent.com/4714680/79814363-4397fd00-83a8-11ea-88aa-c02a05b568e0.png)
I meant bottom seekbar(progress bar)

**Comment by jsanford8** [comment]
Hi @nvhaiwork - I'm a little bit confused; this project is a performance analytics tracking SDK to be added to ExoPlayer, but does not include any UI components or controls. As such, I don't think that our project is responsible for the issue that you're seeing here.

Are you saying that when you initialize Mux's SDK that the controls stop functioning as they did before?

**Comment by nvhaiwork** [comment]
I'm not sure, I did not try ExoPlayer before. I just tried your example and saw the issue.
