### ISSUE TITLE
Mux Plugin Version shows 1.5.0 in Mux dashboard even though v.2.0.0 updated (2.11.1 AAR)

### ISSUE THREAD

**Issue by kai-sarawut** [muxinc/mux-stats-sdk-exoplayer#58]
![image](https://user-images.githubusercontent.com/15886164/98500546-5fe58380-227f-11eb-827e-ccbb62bab57e.png)

What does the Mux Plugin Version should be? After  the 2.0.0 (2.11.1 AAR) integration, we just expect to see version number change to 2.0.0. We would like to be confirmed the correct version of the Mux plugin. Thank you.

**Comment by jsanford8** [comment]
Hello - thanks for reporting this; the version was inadvertently not updated in the latest release. We will fix this in the next release coming out this week!

**Comment by kai-sarawut** [comment]
@jsanford8 Thank you for the confirmation.
