### ISSUE TITLE
Issue with Video startup time

### ISSUE THREAD

**Issue by Discovery-JSwapnil** [muxinc/mux-stats-sdk-exoplayer#61]
We are using latest `v2.0.0` version of the Mux SDK (mux-r2.11.1.aar) with Exoplayer 2.11.0 and IMA extension SDK 2.11.0

On our dashboard we are getting more numbers of `Exit Before Video Starts` percentage. In our investigations, we found that it is happening because for some of the videos `Video Startup time` is not getting recorded as `playing` event is not tracked though timeline shows that video played. Duration shown on timeline is low as few seconds though. Can you help us with this?

**Comment by james-mux** [comment]
Hi @Discovery-JSwapnil - thanks for reaching out. Could you drop me an e-mail to james@mux.com and we can look into this? Thanks!

**Comment by james-mux** [comment]
Working directly with @Discovery-JSwapnil on this. At this time we are unable to replicate any issue related to Video Start-Up Time within the SDK but we are continuing to investigate an edge case.

**Comment by james-mux** [comment]
This issue should now be resolved from release v2.4.6 onwards. If you upgrade to the latest, any misreporting due to playWhenReady being false, but IMA pre-roll ads being present should be handled as expected from this version forwards.
