### ISSUE TITLE
All types of Renderer issues are not captured

### ISSUE THREAD

**Issue by saurabharora90** [muxinc/mux-stats-sdk-exoplayer#72]
Currently, `MuxStatsExoPlayer` is not capturing all types of `TYPE_RENDERER` errors. It is only capturing errors which are of type `DecoderInitializationException`

Is there any reason others are not being captured?

**Comment by jsanford8** [comment]
Hey @saurabharora90 - thanks for the issue (and the PR, which looks good!). One quick question - we only started out with the DecoderInitializationException as those were the ones that we knew were fatal to playback (e.g. if the decoder can't be initialized, it's not going to be able to play). What other types of `TYPE_RENDERER` errors might occur, and do you know if they will cause playback to fail?

**Comment by saurabharora90** [comment]
>What other types of `TYPE_RENDERER` errors might occur, and do you know if they will cause playback to fail?

I based the PR on two premises:

- Any error sent to [`onPlayerError` is a fatal error and will cause playback to fail](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.EventListener.html#onPlayerError-com.google.android.exoplayer2.ExoPlaybackException-)
- Our internal logging of errors are different than MUX only for `TYPE_RENDERER` errors. Other two, `TYPE_UNEXPECTED` and `TYPE_SOURCE` match completely. We have reports from users of failed playback attempts but on MUX, their views do not turn up as errors (those views have ~0 min of watch time though). One such [instance](https://github.com/google/ExoPlayer/blob/r2.11.8/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L735) is when the player tries to [dequeue the input buffer of the Media Codec](https://github.com/google/ExoPlayer/blob/r2.11.8/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L1053) or deals with the output buffer

**Comment by saurabharora90** [comment]
Hi @jsanford8 

Hope you had a good holiday!

Any updates on this? :)

**Comment by jsanford8** [comment]
Hey @saurabharora90 thanks for following up! We had to get a real quick fix out for the large size of our built AAR files, but this will be following up shortly with another release once we have a quick chance to test it.

**Comment by saurabharora90** [comment]
Closing the issue as the PR was merged :)

**Comment by saurabharora90** [comment]
Following up with the results of this @jsanford8:

Code 1 errors with the new Mux SDK with this fix:

<img width="1010" alt="Screenshot 2021-02-18 at 3 24 01 PM" src="https://user-images.githubusercontent.com/1703474/108320186-6b8d0280-71fd-11eb-93a8-a469f9747322.png">


Code 1 errors earlier:

<img width="916" alt="Screenshot 2021-02-18 at 3 24 14 PM" src="https://user-images.githubusercontent.com/1703474/108320204-72b41080-71fd-11eb-986f-44d74e06140c.png">
