### ISSUE TITLE
AAR file is 16.6 MB in size

### ISSUE THREAD

**Issue by ThomasCZ** [muxinc/mux-stats-sdk-exoplayer#75]
AAR file of the latest version 2.3.0 has size 16.6MB. It is caused by test file _sample-1280x720.mkv_ in assets folder.

**Comment by Discovery-JSwapnil** [comment]
Kindly look into this on priority and provide us lesser sized AAR files. Thank you.

**Comment by jsanford8** [comment]
Hey @ThomasCZ @Discovery-JSwapnil - thanks for reporting this. We have found the issue, and will be releasing a new version shortly. I'll update this ticket once it's release.

**Comment by jsanford8** [comment]
This has been fixed in v2.3.1 release.
