### ISSUE TITLE
AAR lib contains undesirable resources

### ISSUE THREAD

**Issue by ThomasCZ** [muxinc/mux-stats-sdk-exoplayer#78]
AAR library contains application icon, layout and other undesirable resources. Please look into this on priority. Thank you.

![resources](https://user-images.githubusercontent.com/7516715/104297065-b14e0100-54c2-11eb-90dc-567b502024e0.png)

**Comment by skidder** [comment]
This has been fixed in v2.4.4, marking as closed.
