### ISSUE TITLE
Project with Mux 0.4.4 does not build 

### ISSUE THREAD

**Issue by AdamGrzybkowski** [muxinc/mux-stats-sdk-exoplayer#8]
After updating mux-r2.8.0 to 0.4.4 the project does not build.

Error 
```
Execution failed for task ':app:transformClassesWithInstantRunForStagingDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for com/google/ads/interactivemedia/v3/api/AdErrorEvent$AdErrorListener
```

In the [integration guide](https://docs.mux.com/docs/android-integration-guide) there is nothing mentioned about IMA. Is this required?

**Comment by jsanford8** [comment]
Hey @AdamGrzybkowski - when we released support for the IMA SDK (to track ad playback), we inadvertently introduced a dependency on the IMA SDK. This was not intended, and we're working on fixing it in a future version.

**Comment by jsanford8** [comment]
Let us know if you need to reopen this, but with #20 we have updated the build process a bit, and should hopefully have resolved this.
