### ISSUE TITLE
Use Player version and Player name from CustomerPlayerData config

### ISSUE THREAD

**Issue by Oziomajnr** [muxinc/mux-stats-sdk-exoplayer#91]
In this SDK, the class `com.mux.stats.sdk.core.model.CustomerPlayerData `allows us to set the player name and player version but these values are not being used. In `com.mux.stats.sdk.muxstats.MuxBaseExoPlayer ` the player name and player version are hardcoded as `"ExoPlayer"` and `ExoPlayerLibraryInfo.VERSION` respectively. 

In some cases this is not desired, for example we integrated MUX in our player library  and we would like to display our player name and version on the MUX dashboard instead of Exo player. 

A solution would be to create a custom implementation of MUX SDK or forking this repository and changing those values, but these solutions are an overkill for something that simple. 

Can this SDK use the values set in CustomerPlayerData  for player version and player name and maybe default to the ExoPlayer values when these are not provided.

**Comment by skidder** [comment]
@Oziomajnr - Thank you for opening an issue! Mux Data distinguishes between the names & versions of player tech (e.g. VideoJS, ExoPlayer) and customer player info (e.g. the name & version of your player). Full descriptions of all supported fields are provided in our [docs](https://docs.mux.com/docs/data-reference#general-metadata).

The hardcoded values you referred to (`ExoPlayer` and `ExoPlayerLibraryInfo.VERSION`) are used to populate the `Player Software` and `Player Software Version`. These values come from the SDK to ensure consistency in naming and versioning.

The `CustomerPlayerData` fields end up in the `Player Name` and `Player Version` in Mux Data, which are unique to each customer, and ought to be working. Would you please check whether this is the case? If not, can you provide some details about the SDK version you're using?

Thanks!

**Comment by Oziomajnr** [comment]
Thanks for the clarification, I can confirm the `Player Name` and `Player Version` is populated in the dashboard and its different from `Player Software` and `Player Software Version`. 

I was using a trial account and I did not see them as separate fields, probably  `Player Name` and `Player Version`  are not  visible on the dashboard for trial accounts but from our premium account this is not the case. 
So this issue is not an issue and it can be closed.
