### ISSUE TITLE
Support ExoPlayer 2.13

### ISSUE THREAD

**Issue by indieboyalex** [muxinc/mux-stats-sdk-exoplayer#95]
We need a version that supports ExoPlayer 2.13.

We tried using 2.13 with the 2.12 version of the plugin but this caused crashes when playing video (player worked fine without the plugin so it's not the player implementation)

**Comment by skidder** [comment]
@iNdieboyjeff Thank you for the issue, we added support for Exoplayer r2.13.1+ in [release 2.4.5](https://github.com/muxinc/mux-stats-sdk-exoplayer/releases/tag/v2.4.5) of our SDK.

**Comment by skidder** [comment]
Fixed by #98
